ROS Parameters: Add boat simulator ROS parameters
UBCSailbot/sailbot_workspace pull request #178
Opened 2023-10-14 18:14 UTC by chrischang5

### Description

- Resolves https://github.com/UBCSailbot/boat_simulator/issues/37
- Implementation of reading these parameters in the `boat_simulator` is done in https://github.com/UBCSailbot/boat_simulator/pull/43

### Verification

- [ ] See https://github.com/UBCSailbot/boat_simulator/pull/43 for verification steps of reading in parameters in the `boat_simulator`

### Resources

- [ROS2 YAML parameter structure](https://roboticsbackend.com/ros2-yaml-params/#Why_using_YAML_for_ROS2_params)
- [ROS2 Parameter docs](https://docs.ros.org/en/humble/Concepts/Basic/About-Parameters.html)

2023-10-14 21:02 UTC, patrick-5546 approved these changes
LGTM infrastructure wise, I'll trust @DFriend01 to verify that it works

2023-10-14 22:53 UTC, DFriend01 requested changes
Just some comments on the parameter ranges.

2023-10-14 22:53 UTC, DFriend01 commented on src/global_launch/config/globals.yaml
When using interval notation, let's try to be more mathematically specific (i.e. use `(` for non-inclusive boundaries and `[` for inclusive boundaries). Remember for infinity, use `(` (i.e. for `DOUBLE_MAX`, `DOUBLE_MIN`)

2023-10-14 22:53 UTC, DFriend01 commented on src/global_launch/config/globals.yaml
> +         fixed_angle_deg: 0.0 # Only used if rudder actuation is disabled: [0.0, 360.0]
Range should be [-45, 45]

2023-10-14 22:53 UTC, DFriend01 commented on src/global_launch/config/globals.yaml
> +         actuation_execution_period_sec: 0.5 # How often the rudder action server routine's main loop executes: [0.0, MAX_DOubLE]
Should not include zero

2023-10-14 22:53 UTC, DFriend01 commented on src/global_launch/config/globals.yaml
> +            buffer_size: 50 # [0, MAX_INT]
Should not include zero (start from 1)

2023-10-14 22:53 UTC, DFriend01 commented on src/global_launch/config/globals.yaml
> +         fixed_angle_deg: 0.0 # Only used if actuation is disabled: [0.0, 360.0]
Let's make the range symmetric => [-180, 180)

2023-10-14 22:53 UTC, DFriend01 commented on src/global_launch/config/globals.yaml
> +         actuation_speed_deg_per_sec: 0.1 # Only used if actuation is enable: [0.0, MAX_DOUBLE]
Should not include zero

2023-10-14 22:53 UTC, DFriend01 commented on src/global_launch/config/globals.yaml
> +         actuation_request_period_sec: 10.0 # How often the sail action server requests a wingsail actuation: [0.0, MAX_DOUBLE]
Should not include zero

2023-10-18 01:11 UTC, chrischang5 commented on src/global_launch/config/globals.yaml
> +            buffer_size: 50 # [0, MAX_INT]
Will update value to reflect this then.

2023-10-18 01:26 UTC, DFriend01 commented
@chrischang5 I realize you are working on this right now, but can you create a `README.md` file inside of the `config` directory instead, of defining the configuration parameters?

For each parameter, can you add:
- An explanation of what the parameter is
- Its type
- The range of acceptable values

The config file is starting to look a little messy, so perhaps this would be a better approach to documenting these values. What do you think?

2023-10-18 06:25 UTC, chrischang5 commented
> @chrischang5 I realize you are working on this right now, but can you create a `README.md` file inside of the `config` directory instead of the configuration file itself?
> 
> For each parameter, can you add:
> 
> * An explanation of what the parameter is
> * Its type
> * The range of acceptable values
> 
> The config file is starting to look a little messy, so perhaps this would be a better approach to documenting these values. What do you think? I trust that you can devise an acceptable format for the README.

README seems like a better solution. One drawback is that it's a separate place we need to maintain alongside the config file, but I think its' better than a messy config file.

2023-10-18 06:26 UTC, chrischang5 commented
We should spend more time in the design phase next time to avoid changing implementations all the time. Might have made this process smoother.

2023-10-18 18:09 UTC, DFriend01 commented
I updated the configuration parameter descriptions. @patrick-5546 did you want to take a quick look?

2023-10-18 18:49 UTC, patrick-5546 commented
Looks great! A couple of suggestions
- Add the README to the docs site
- Alphabetize the parameters

2023-10-20 01:06 UTC, DFriend01 approved these changes

2023-10-20 01:11 UTC, merged