Add configuration for data collection node
UBCSailbot/sailbot_workspace pull request #222
Opened 2023-12-09 04:49 UTC by eomielan

### Description

- Update the `globals.yaml` file to align with the changes introduced by the new data collection node for the boat simulator.

2023-12-09 16:30 UTC, patrick-5546 reviewed
Please update the README as well
https://github.com/UBCSailbot/sailbot_workspace/blob/0b38685f034286b6f6bab56293228c5294375d70/src/global_launch/config/README.md

2024-01-01 00:52 UTC, DFriend01 requested changes
Remove the comments from the `globals.yaml`, and instead update the README file in `config/` and add documentation about each input there.

2024-01-30 09:23 UTC, DFriend01 approved these changes

2024-01-30 09:23 UTC, DFriend01 commented
@patrick-5546 Please approve

2024-01-30 19:25 UTC, patrick-5546 approved these changes

2024-01-30 20:39 UTC, merged