LUT mappings added
UBCSailbot/sailbot_workspace pull request #234
Opened 2024-01-27 23:20 UTC by evannawfal

### Description

- Resolves https://github.com/UBCSailbot/controller/issues/22

### Verification
https://github.com/UBCSailbot/controller/pull/26

2024-01-30 09:21 UTC, DFriend01 requested changes

2024-01-30 09:21 UTC, DFriend01 commented on src/global_launch/config/README.md
> +- _Description_: The reynolds number of the boat.
Reynold's number refers to fluids, not the boat

2024-03-06 22:22 UTC, DFriend01 approved these changes

2024-03-06 22:46 UTC, patrick-5546 approved these changes

2024-03-10 17:44 UTC, merged