Connecting CAN Frames to ROS, issue #326
UBCSailbot/sailbot_workspace pull request #333
Opened 2024-03-19 19:20 UTC by lross03

### Description

- Implemented pairing of CAN frames with their respective ROS publishing functions.

2024-03-19 19:31 UTC, lross03 commented
In the filtered wind sensor publishing function, I was getting an error saying I was narrowing the type conversion from int to int16 when I was calculating the average direction. As far as I can tell, direction is an int16 in the custom interface, so I don't know why I was getting this error. I added a nolint (bugprone-narrowing-conversions) for now. 

I also wasn't sure how to approach finding the correct generic sensor from the generic sensor custom interface, as generic sensors are not in the can_frame_parser, so I used the same method as the battery publishing function and assumed that the sensor will be in the generic_sensors array from custom interfaces.

2024-03-23 20:27 UTC, hhenry01 requested changes
Please address the sections marked with `TODO(lross03)`

2024-06-15 05:57 UTC, samdai01 requested changes
issue with data size of ship width

2024-06-15 05:57 UTC, samdai01 commented on src/network_systems/projects/can_transceiver/src/can_frame_parser.cpp
> +    uint8_t  raw_width;
According to `CAN Frames`, the width is of type `uint16_t`

2024-06-15 14:57 UTC, samdai01 commented on src/network_systems/projects/can_transceiver/src/can_frame_parser.cpp
> +    std::memcpy(&raw_width, cf.data + BYTE_OFF_WIDTH, sizeof(int8_t));
Please change this to copy `uint16_t` to `raw_width`

2024-07-13 14:59 UTC, samdai01 approved these changes

2024-07-13 15:12 UTC, merged