[WEB] DATA FOR RESEARCHERS
UBCSailbot/sailbot_workspace pull request #346
Opened 2024-03-29 01:52 UTC by JordanChen123

### Description

- Resolves #294 

### Verification

- [ ] 

### Resources

-

2024-03-29 05:20 UTC, jahn18 requested changes
After addressing the comment, please also to make sure to run `npm format` and `npm lint`!

2024-03-29 05:20 UTC, jahn18 commented on src/website/views/components/Header/header.module.css
I noticed the text "UBC Sailbot" on the header got centered: 

![image](https://github.com/UBCSailbot/sailbot_workspace/assets/59242538/f60096bf-8eb5-475f-8f34-2e6d499a09ae)

Could we place the text on the left side as we had previously? The position of the info button is perfectly fine.

2024-03-30 02:30 UTC, JordanChen123 commented on src/website/views/components/Header/header.module.css
Done !

2024-03-30 04:49 UTC, jahn18 approved these changes
Thanks Jordan! 😄 Looks good

2024-04-03 18:52 UTC, merged