kristatraboulay/426-update-physics-engine-node-PR
UBCSailbot/sailbot_workspace pull request #444
Opened 2024-10-26 20:39 UTC by kristatraboulay

### Description

- Resolves #426 by updating boat state to use wind sensor data from a private instance of the SimWindSensor class.

### Verification

- Successfully built boat_simulator package

2024-10-26 21:31 UTC, eomielan requested changes
Looks good, just a couple comments.

2024-10-26 21:31 UTC, eomielan commented on src/boat_simulator/boat_simulator/nodes/physics_engine/physics_engine_node.py
> +        self.update(wind=self.__wind_generator.next())
I believe you could use the public setter provided for this attribute. So you could replace the following code with `self.__sim_wind_sensor = self.__wind_generator.next()`. See https://github.com/UBCSailbot/sailbot_workspace/blob/3bf448c71e83f4cc4cbba4d6527c837414a02b9c/src/boat_simulator/boat_simulator/common/sensors.py#L126 in the `SimWindSensor` class. See this [link](https://www.freecodecamp.org/news/python-property-decorator/) for more details on python getters and setters.

2024-10-26 22:20 UTC, eomielan commented on src/boat_simulator/boat_simulator/nodes/physics_engine/physics_engine_node.py
> +        sim_wind_noise_stdev = List[Scalar] = [-10.0, 10.0]
The default noise of `[1.0, 1.0]` in the `SimWindSensor` constructor seems reasonable for wind. Could you please adjust this to use the default.

2024-10-26 22:31 UTC, eomielan commented on src/boat_simulator/boat_simulator/nodes/physics_engine/physics_engine_node.py
> +        self.__sim_wind_sensor.wind = self.__wind_generator.next()
I think it might be best to move this line to the beginning of `__update_boat_state()` and remove this method.

2024-10-26 23:05 UTC, eomielan commented
Changes look good! We'll hold off on merging this PR until #447 is completed to ensure fluid dimensions align with the expected dimensions in the wind sensor.

2024-11-02 22:52 UTC, eomielan commented
Now that #447 is merged please update you branch, re-build the boat simulator package and re-run it just to verify no crashes. Once this is complete please leave a comment on the PR and I can approve.

2024-11-02 22:59 UTC, kristatraboulay commented
Successfully built boat simulator and ran roslaunch

2024-11-02 23:02 UTC, eomielan approved these changes
Looks good!

2024-11-23 18:36 UTC, merged