[NET] Local Transceiver - receive function and testing
UBCSailbot/sailbot_workspace pull request #465
Opened 2024-11-30 19:21 UTC by Jng468

### Description

- Completed receive function 

### Verification

- Unit tested by sending waypoints data

2025-01-11 03:26 UTC, samdai01 commented on src/network_systems/projects/local_transceiver/src/local_transceiver.cpp
> +        std::stringstream test;
not sure what this test string is for

2025-01-11 04:54 UTC, samdai01 requested changes
See comments added

2025-01-11 04:54 UTC, samdai01 commented on src/network_systems/projects/local_transceiver/src/local_transceiver.cpp
> +        std::regex re(
https://docs.groundcontrol.com/iot/rockblock/user-manual/at-commands

According to the above link, the output of `AT+SBDRB` should be just the message length, binary message, and checksum

please explain what the regex where we parse for name= and filename= is doing, if it currently works with the virtual iridium, then its fine

if it doesnt work when we connect to the actual iridium, then we might need to change it when we are working with the HW

2025-01-11 04:54 UTC, samdai01 commented on src/network_systems/projects/local_transceiver/src/local_transceiver.cpp
> +        std::stringstream test;
not sure what this test string is for

2025-01-11 04:54 UTC, samdai01 commented on src/network_systems/projects/local_transceiver/test/test_local_transceiver.cpp
> +        std::cout << "Latitude of the first waypoint: " << global_path.waypoints(0).latitude() << std::endl;
please use asserts to check:
- the number of waypoints
- the value of each waypoint (lat + lon)

2025-01-11 04:54 UTC, samdai01 commented on src/website/views/components/DropDown/dropdown.module.css
> -@import 'https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap';
please update and remove this file from changes, its part of website

2025-01-11 04:59 UTC, samdai01 commented
Could you also change `TIMER_INTERVAL` so that we are not calling publish every 500ms? a value such as 5 minutes for now should be good

2025-01-11 23:29 UTC, Jng468 commented on src/network_systems/projects/local_transceiver/test/test_local_transceiver.cpp
> +        std::cout << "Latitude of the first waypoint: " << global_path.waypoints(0).latitude() << std::endl;
Assert statements have been added.

2025-01-11 23:30 UTC, Jng468 commented on src/network_systems/projects/local_transceiver/src/local_transceiver.cpp
> +        std::stringstream test;
Test string is removed.

2025-01-11 23:37 UTC, Jng468 commented on src/website/views/components/DropDown/dropdown.module.css
> -@import 'https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap';
Complete. This file is now up to date with main.

2025-01-11 23:37 UTC, Jng468 commented on src/network_systems/projects/local_transceiver/src/local_transceiver.cpp
> +        std::regex re(
As discussed, changes will be made when we are working with the HW.

2025-01-18 22:08 UTC, samdai01 approved these changes

2025-01-18 22:10 UTC, merged