User/medhansh/desired heading
UBCSailbot/sailbot_workspace pull request #467
Opened 2024-11-30 21:58 UTC by MC6527medhansh

### **Description**
- Resolves #283  
- Implemented the functionality to compute and publish the desired heading from the current boat position to the next waypoint.

---

### **Verification**
- [ ] Ensure the desired heading is correctly calculated using the `Geod` class from the `pyproj` library for distance and azimuth computation.
- [ ] Validate that the system updates the waypoint index correctly when the boat reaches a waypoint using a threshold distance.
- [ ] Check scenarios where the path is updated to ensure the waypoints start from the boat's current position.

---

### **Resources**
- UBC Sailbot Documentation
- Pyproj Documentation for Geodesic Calculations (https://pyproj4.github.io/pyproj/stable/api/geod.html)

---

2025-01-11 21:43 UTC, FireBoyAJ24 requested changes

2025-01-11 21:43 UTC, FireBoyAJ24 commented on src/local_pathfinding/local_pathfinding/node_navigate.py
> +        # update waypoint
Comments are redundant

2025-01-11 21:43 UTC, FireBoyAJ24 commented on src/local_pathfinding/local_pathfinding/node_navigate.py
> +        boat_lat = self.gps.position.lat_lon.latitude
The boat latitude and longitude could be placed in a tuple and parsed into the functions

2025-01-11 21:43 UTC, FireBoyAJ24 commented on src/local_pathfinding/local_pathfinding/node_navigate.py
> +        GEODESIC = Geod(ellps="WGS84")
You could add this statements the top of the file

2025-01-11 21:59 UTC, FireBoyAJ24 requested changes

2025-01-11 21:59 UTC, FireBoyAJ24 commented on src/local_pathfinding/local_pathfinding/node_navigate.py
> +    def calculate_angle(lat1, lon1, lat2, lon2):
The calculate_distance and calculate_angle function looks redundant as the functions are acting as wrappers to the geodesic.inv function. You could add the geodesic.inv function to the 'get_angle' function.

2025-01-11 21:59 UTC, FireBoyAJ24 commented on src/local_pathfinding/local_pathfinding/node_navigate.py
> +            # then update the next local waypoint by increasing index by 1
You can remove this comment.

2025-02-19 18:23 UTC, SPDonaghy commented on src/local_pathfinding/local_pathfinding/node_navigate.py
> +        boat_lat = self.gps.position.lat_lon.latitude
Please use HelperLatLon type to store lat/lons whenever possible.

2025-03-25 04:18 UTC, closed without merging

2025-03-25 04:18 UTC, SPDonaghy commented
closing as same issue is resolved with #527